swagger: '2.0'
info:
  version: 1.0.0
  title: 'ISB Aquaponics API'
  license:
    name: LGPL V3.0
    url: 'http://www.gnu.org/licenses/lgpl-3.0.en.html'

host: 'localhost:5000'

schemes:
  - http

securityDefinitions:
  google_oauth2:
    type: oauth2
    description:
      3rd party OAuth2 authorization is used. Google OAuth2 is the default provider.
    in: header
    name: Authorization
    scopes: ['email']
    flow: accessCode
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth?client_id=75692667349-39hlipha81a3v40du06184k75ajl8u4u.apps.googleusercontent.com&scope=email%20profile&redirect_uri=http%3A%2F%2Flocalhost:8080&response_type=token'
    tokenUrl: 'https://www.googleapis.com/oauth2/v3/token'

basePath: /api/v1.0
paths:
  /systems:
    get:
      description:
        "Retrieve brief information bout the authenticated user's `System` objects."
      security:
        - google_oauth2:
            - email
      produces:
        - application/json
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/SystemInfos'
    post:
      description:
        "create a new system entry"
      security:
        - google_oauth2:
          - email
      produces:
        - application/json
      parameters:
        - name: create-spec
          in: body
          description: measurements to add
          required: true
          schema:
            $ref: '#/definitions/CreateSystemSpec'
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/StatusResponse'

  /system/{system_uid}:
    get:
      description:
        Retrieves detail information about the specified `System` object
      security:
        - google_oauth2:
            - email
      produces:
        - /application/json
      parameters:
        - name: system_uid
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/SystemDetails'
    post:
      description:
        updates the specified `System` information
      security:
        - google_oauth2:
          - email
      produces:
        - /application/json
      parameters:
        - name: system_uid
          in: path
          required: true
          type: string
        - name: update_data
          in: body
          description: information to update
          required: false
          schema:
            $ref: "#/definitions/UpdateSystemSpec"
      responses:
        '200':
          description: status response
          schema:
            $ref: "#/definitions/StatusResponse"
                      
  /measurements/{system_uid}:
    post:
      description:
        Send a set of measurements for storage.
      security:
        - google_oauth2:
            - email
      produces:
        - /application/json
      parameters:
        - name: system_uid
          in: path
          required: true
          type: string
        - name: measurements
          in: body
          description: measurements to add
          required: true
          schema:
            $ref: '#/definitions/Measurements'
      responses:
        '200':
          description:
            successful response
          schema:
            $ref: "#/definitions/StatusResponse"

  /measurements/{system_uid}/{from}/{to}:
    get:
      description:
        Retrieves a set of measurements
      security:
        - google_oauth2:
          - email
      produces:
        - /application/json
      parameters:
        - name: system_uid
          in: path
          required: true
          type: string
        - name: from
          in: path
          type: string
          format: date-time
          required: false
        - name: to
          in: path
          type: string
          format: date-time
          required: false
      responses:
        '200':
          description:
            succesful responses
          schema:
            $ref: '#/definitions/MeasurementData'

  /aquatic_crops:
    get:
      description:
        retrieves a list of all aquatic crops in the system
      produces:
        - /application/json
      responses:
        '200':
          description:
            successful response
          schema:
            $ref: "#/definitions/Catalog"

  /botanic_crops:
    get:
      description:
        retrieves a list of all plant crops in the system
      produces:
        - /application/json
      responses:
        '200':
          description:
            successful response
          schema:
            $ref: "#/definitions/Catalog"

  /techniques:
    get:
      description:
        retrieves a list of all aquaponics techniques in the system
      produces:
        - /application/json
      responses:
        '200':
          description:
            successful response
          schema:
            $ref: "#/definitions/Catalog"

definitions:
  Catalog:
    description:
      a list of catalog entries
    properties:
      entries:
        type: array
        items:
          title: CatalogEntry
          description:
            a catalog entry
          type: object
          required:
            - id
            - name
          properties:
            id:
              description:
                database id
              type: number
              format: int
            name:
              description:
                entry name
              type: string

  MeasurementData:
    description:
      a collection of measurement data
    properties:
      alkalinity:
        required: false
        $ref: "#/definitions/MeasurementValues"
      ammonium:
        required: false
        $ref: "#/definitions/MeasurementValues"
      chlorine:
        required: false
        $ref: "#/definitions/MeasurementValues"
      hardness:
        required: false
        $ref: "#/definitions/MeasurementValues"
      light:
        required: false
        $ref: "#/definitions/MeasurementValues"
      nitrate:
        required: false
        $ref: "#/definitions/MeasurementValues"
      nitrite:
        required: false
        $ref: "#/definitions/MeasurementValues"
      o2:
        required: false
        $ref: "#/definitions/MeasurementValues"
      ph:
        required: false
        $ref: "#/definitions/MeasurementValues"
      temp:
        required: false
        $ref: "#/definitions/MeasurementValues"


  MeasurementValues:
    description:
      a collection of measurement values
    type: array
    items:
      type: object
      required:
        - time
        - value
      properties:
        time:
          type: string
          format: date-time
        value:
          type: number
          format: float

  Measurements:
    description:
      A list of measurements.
    properties:
        measurements:
          type: array
          items:
            title: Measurement
            description:
              Unit of measurement data.
            type: object
            required:
              - time
            properties:
              time:
                description:
                  time of measurement in the format `YYYY-MM-DDTHH:MM:SSZ`
                  "http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14"
                type: string
                format: date-time
              o2:
                description: dissolved oxygen concentration in mg/l
                type: number
                format: float
              temp:
                description: temperature in degree Celsius
                type: number
                format: float
              light:
                description: light intensity in lux
                type: number
                format: float
              ph:
                description: pH value
                type: number
                format: float
              ammonium:
                description: ammonium concentration in mg/l
                type: number
                format: float
              nitrate:
                description: nitrate concentration in mg/l
                type: number
                format: float
              nitrite:
                description: nitrite concentration in mg/l
                type: number
                format: float

  SystemDetails:
    description:
        Detail information for an aquaponics system
    properties:
      name:
        type: string
      creation_time:
        type: string
        format: date-time
      start_date:
        type: string
        format: date
      aqx_technique:
        type: string
      image_url:
        type: string
      aquatic_organisms:
        type: array
        items:
          title: AquaticOrganisms
          type: object
          properties:
            name:
              type: string
            num:
              type: integer
            crops:
              type: array
              items:
                title: Crops
                type: object
                properties:
                  name:
                    type: string
                  num:
                    type: integer

  SystemInfos:
    description:
      List of `SystemInfo` objects
    properties:
      systems:
        type: array
        items:
          title: SystemInfo
          type: object
          description:
            Brief information about a system
          properties:
            uid:
              type: string
            name:
              type: string
            thumb_url:
              type: string

  CreateSystemSpec:
    description:
      information for creating a system
    properties:
      name:
        type: string
        
  UpdateSystemSpec:
    description:
      information for updating a system
    properties:
      name:
        type: string

  StatusResponse:
    description:
      Simple ok status
    properties:
      status:
        type: string
        description:
          status code
      message:
        type: string
        description:
          detail description of the message
      