/* Users and Aquaponics systems */
create table if not exists users (id integer primary key not null auto_increment, google_id varchar(100) not null, email varchar(100) not null, default_site_location varchar(80), creation_time timestamp not null default now(), status integer not null default 0);
create table if not exists systems (id integer primary key not null auto_increment, user_id integer not null references users, name varchar(100) not null, system_uid varchar(40) not null, creation_time timestamp not null default now(), start_date date, status integer not null default 0, aqx_technique_id integer references aqx_techniques);

create table if not exists aquatic_organisms (id integer primary key not null auto_increment, name varchar(100) not null);
create table if not exists crops (id integer primary key not null auto_increment, name varchar(100) not null);
create table if not exists aqx_techniques (id integer primary key not null auto_increment, name varchar(100) not null);
create table if not exists growbed_media (id integer primary key not null auto_increment, name varchar(100) not null);

create table if not exists system_access (system_id integer not null references systems, user_id integer not null references users, can_read boolean default true, can_modify boolean default true, can_measure_web boolean default true, can_measure_api boolean default true, primary key (system_id, user_id));

create table if not exists system_aquatic_organisms (system_id integer not null references systems, organism_id integer not null references aquatic_organisms, num integer not null default 0, primary key (system_id, organism_id));
create table if not exists system_crops (system_id integer not null references systems, crop_id integer not null references crops, num integer not null default 0, primary key (system_id, crop_id));
create table if not exists system_gb_media (system_id integer not null references systems, gb_media_id integer not null references growbed_media, num integer not null default 0, primary key (system_id, gb_media_id));

/*
  This is just to illustrate the pattern. The tables are generated by the application
  on a per-system basis. This is a solution that can scale in an easier way and
  will not run into performance problems quite so quickly.
  To get tuples of the values, we can join the tables using the timestamp as the join key.
*/

/*
create table if not exists aqxs_ammonium_aa56fa203bcb11e58c8864273763ec8b (time timestamp primary key not null, value decimal(13,10) not null);
create table if not exists aqxs_o2_aa56fa203bcb11e58c8864273763ec8b (time timestamp primary key not null, value decimal(13,10) not null);
create table if not exists aqxs_ph_aa56fa203bcb11e58c8864273763ec8b (time timestamp primary key not null, value decimal(13,10) not null);
create table if not exists aqxs_nitrate_aa56fa203bcb11e58c8864273763ec8b (time timestamp primary key not null, value decimal(13,10) not null);
create table if not exists aqxs_light_aa56fa203bcb11e58c8864273763ec8b (time timestamp primary key not null, value decimal(13,10) not null);
create table if not exists aqxs_temp_aa56fa203bcb11e58c8864273763ec8b (time timestamp primary key not null, value decimal(13,10) not null);
*/

create unique index crop_name_index on crops (name);
create unique index aq_org_name_index on aquatic_organisms (name);
create unique index aqx_tech_name_index on aqx_techniques (name);
create unique index gb_media_name_index on growbed_media (name);
